### ISSUE TITLE
Criação de comando de boas-vindas

### ISSUE THREAD

**Issue by joaovictorsoars** [umroboporaluno/discord-bot#5]
Deve ser criado um novo comando do bot para dar as boas-vindas aos novos alunos do curso.
O comando deve ter um parâmetro para especificar para qual tipo de curso (EM, Gradução ou Professores).
O comando deve ser apenas utilizável para certo nível de cargo (pode-se adicionar uma falha dizendo que não tem privilégios para isso caso o cargo não seja aquele)

Os cargos a seguir poderão digitar o comando:
- Líderes

A mensagem em questão será:
![Imagem do WhatsApp de 2024-04-09 à(s) 20 18 24_719a020b](https://github.com/umroboporaluno/discord-bot/assets/63375574/42d2576c-555b-423b-9dad-5fc5c512df66)

Detalhes:
- Atualmente, o ensino médio se encontra no sábado dia 13 8h30 ate 11h30 LAB 1
- Graduandos é sexta dia 12
- Professores ainda não sei (pode skipar por enquanto)

**Comment by luissssmartins** [comment]
Comando feito!
